#pragma once
#include <iostream>
#include <iomanip>
#include <fstream>
#include <sstream>
#include <codecvt>

#include <map>
#include <vector>
#include <set>
#include <string>

using std::map;
using std::vector;
using std::set;
using std::string;
using std::cout;
using std::endl;
using std::setw;
using std::ifstream;
using std::ofstream;
using std::stringstream;
using std::istringstream;
using std::getline;
using std::exception;
using std::transform;
using std::left;
using std::quoted;
using std::wcout;
using std::wifstream;
using std::wofstream;
using std::wstringstream;
using std::wistringstream;
using std::wstring;
using std::wstring_convert;
using std::codecvt_utf8_utf16;